# Japanese translations for savanna.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the savanna project.
#
# Translators:
# Kinjo <shinobu.kinjo@oist.jp>, 2013
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2013
msgid ""
msgstr ""
"Project-Id-Version:  Savanna\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-02-03 06:09+0000\n"
"PO-Revision-Date: 2014-01-17 06:20+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Japanese "
"(http://www.transifex.com/projects/p/openstack/language/ja/)\n"
"Plural-Forms: nplurals=1; plural=0\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: savanna/openstack/common/eventlet_backdoor.py:140
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr "Eventlet backdoorは、プロセス%(pid)dの%(port)sをリスニングしています。"

#: savanna/openstack/common/exception.py:103
msgid "Uncaught exception"
msgstr "見つかっていない例外"

#: savanna/openstack/common/excutils.py:62
#, python-format
msgid "Original exception being dropped: %s"
msgstr "除去される元の例外: %s"

#: savanna/openstack/common/excutils.py:91
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "予期せぬ例外が、%d回()発生しました。再試行中。"

#: savanna/openstack/common/fileutils.py:63
#, python-format
msgid "Reloading cached file %s"
msgstr "キャッシュ・ファイル %s を再ロードしています"

#: savanna/openstack/common/gettextutils.py:263
msgid "Message objects do not support addition."
msgstr ""

#: savanna/openstack/common/gettextutils.py:272
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: savanna/openstack/common/lockutils.py:103
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "取得したロック `%s` を解放できませんでした"

#: savanna/openstack/common/lockutils.py:168
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: savanna/openstack/common/lockutils.py:177
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: savanna/openstack/common/lockutils.py:187
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: savanna/openstack/common/lockutils.py:205
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: savanna/openstack/common/lockutils.py:209
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: savanna/openstack/common/lockutils.py:247
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: savanna/openstack/common/lockutils.py:251
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: savanna/openstack/common/log.py:313
#, python-format
msgid "Deprecated: %s"
msgstr "非推奨: %s"

#: savanna/openstack/common/log.py:416
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: savanna/openstack/common/log.py:467
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "syslog 機能は次のいずれかでなければなりません: %s"

#: savanna/openstack/common/log.py:654
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "推奨されない構成への致命的な呼び出し: %(msg)s"

#: savanna/openstack/common/loopingcall.py:82
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr "タスクの実行が間隔より %s 秒長くかかりました"

#: savanna/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "一定期間の呼び出しループ"

#: savanna/openstack/common/loopingcall.py:129
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: savanna/openstack/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr "動的呼び出しループ"

#: savanna/openstack/common/periodic_task.py:41
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr "定期タスク作成時の予期しない引数: %(arg)s。"

#: savanna/openstack/common/periodic_task.py:132
#, python-format
msgid "Skipping periodic task %(task)s because its interval is negative"
msgstr "タスクの間隔が負であるため、定期タスク %(task)s をスキップしています"

#: savanna/openstack/common/periodic_task.py:137
#, python-format
msgid "Skipping periodic task %(task)s because it is disabled"
msgstr "タスクが使用不可であるため、定期タスク %(task)s をスキップしています"

#: savanna/openstack/common/periodic_task.py:175
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr "定期タスク %(full_task_name)s の実行中"

#: savanna/openstack/common/periodic_task.py:184
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr "%(full_task_name)s 中のエラー: %(e)s"

#: savanna/openstack/common/processutils.py:58
msgid "Unexpected error while running command."
msgstr ""

#: savanna/openstack/common/processutils.py:61
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: savanna/openstack/common/processutils.py:139
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr "utils.execute の不明なキーワード引数を受け取りました: %r"

#: savanna/openstack/common/processutils.py:145
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: savanna/openstack/common/processutils.py:154
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "コマンド実行(subprocess): %s"

#: savanna/openstack/common/processutils.py:187
#: savanna/openstack/common/processutils.py:259
#, python-format
msgid "Result was %s"
msgstr "コマンド実行結果： %s"

#: savanna/openstack/common/processutils.py:199
#, python-format
msgid "%r failed. Retrying."
msgstr "%r が失敗しました。再試行しています。"

#: savanna/openstack/common/processutils.py:238
#, python-format
msgid "Running cmd (SSH): %s"
msgstr "コマンド（SSH)を実行: %s"

#: savanna/openstack/common/processutils.py:240
msgid "Environment not supported over SSH"
msgstr "環境は SSH でサポートされていません"

#: savanna/openstack/common/processutils.py:244
msgid "process_input not supported over SSH"
msgstr "SSH で process_input は サポートされていません"

#: savanna/openstack/common/service.py:166
#: savanna/openstack/common/service.py:384
msgid "Full set of CONF:"
msgstr "CONF のフルセット:"

#: savanna/openstack/common/service.py:175
#: savanna/openstack/common/service.py:269
#, python-format
msgid "Caught %s, exiting"
msgstr "%s が見つかりました。終了しています"

#: savanna/openstack/common/service.py:187
msgid "Exception during rpc cleanup."
msgstr ""

#: savanna/openstack/common/service.py:238
msgid "Parent process has died unexpectedly, exiting"
msgstr "親プロセスが予期せずに停止しました。終了しています"

#: savanna/openstack/common/service.py:275
msgid "Unhandled exception"
msgstr "未処理例外"

#: savanna/openstack/common/service.py:308
msgid "Forking too fast, sleeping"
msgstr "fork が早すぎます。スリープ状態にしています"

#: savanna/openstack/common/service.py:327
#, python-format
msgid "Started child %d"
msgstr "子 %d を開始しました"

#: savanna/openstack/common/service.py:337
#, python-format
msgid "Starting %d workers"
msgstr "%d ワーカーを開始しています"

#: savanna/openstack/common/service.py:354
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr "子 %(pid)d がシグナル %(sig)d によって強制終了されました"

#: savanna/openstack/common/service.py:358
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr "子 %(pid)s が状況 %(code)d で終了しました"

#: savanna/openstack/common/service.py:362
#, python-format
msgid "pid %d not in child list"
msgstr "pid %d は子リストにありません"

#: savanna/openstack/common/service.py:392
#, python-format
msgid "Caught %s, stopping children"
msgstr "%s が見つかりました。子を停止しています"

#: savanna/openstack/common/service.py:410
#, python-format
msgid "Waiting on %d children to exit"
msgstr "%d 個の子で終了を待機しています"

#: savanna/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr "cert_file が見つかりません: %s"

#: savanna/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr "ca_file が見つかりません: %s"

#: savanna/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr "key_file が見つかりません: %s"

#: savanna/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"サーバーを SSL モードで実行する場合は、cert_file オプション値と key_file "
"オプション値の両方を構成ファイルに指定する必要があります"

#: savanna/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr "無効な SSL バージョン : %s"

#: savanna/openstack/common/wsgi.py:187
msgid "cannot understand JSON"
msgstr "JSON を解釈できません"

#: savanna/openstack/common/wsgi.py:211
msgid "cannot understand XML"
msgstr "XML を解釈できません"

#: savanna/openstack/common/crypto/utils.py:29
msgid "An unknown error occurred in crypto utils."
msgstr ""

#: savanna/openstack/common/crypto/utils.py:36
#, python-format
msgid "Block size of %(given)d is too big, max = %(maximum)d"
msgstr ""

#: savanna/openstack/common/crypto/utils.py:45
#, python-format
msgid "Length of %(given)d is too long, max = %(maximum)d"
msgstr ""

#: savanna/openstack/common/db/exception.py:42
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr "無効なパラメーター: ユニコードは現在のデータベースではサポートされていません。"

#: savanna/openstack/common/db/sqlalchemy/migration.py:191
msgid "version should be an integer"
msgstr "バージョンは整数である必要があります"

#: savanna/openstack/common/db/sqlalchemy/migration.py:214
#, python-format
msgid ""
"Tables \"%s\" have non utf8 collation, please make sure all tables are "
"CHARSET=utf8"
msgstr ""

#: savanna/openstack/common/db/sqlalchemy/migration.py:238
msgid ""
"The database is not under version control, but has tables. Please stamp "
"the current version of the schema manually."
msgstr ""

#: savanna/openstack/common/db/sqlalchemy/session.py:596
msgid "DB exception wrapped."
msgstr "DB 例外が包み込まれました。"

#: savanna/openstack/common/db/sqlalchemy/session.py:665
#, python-format
msgid "Database server has gone away: %s"
msgstr ""

#: savanna/openstack/common/db/sqlalchemy/session.py:743
msgid ""
"This application has not enabled MySQL traditional mode, which means "
"silent data corruption may occur. Please encourage the application "
"developers to enable this mode."
msgstr ""

#: savanna/openstack/common/db/sqlalchemy/session.py:767
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr "SQL 接続が失敗しました。残りの試行回数は %s です。"

#: savanna/openstack/common/db/sqlalchemy/test_migrations.py:63
#, python-format
msgid "Got lock \"%s\""
msgstr ""

#: savanna/openstack/common/db/sqlalchemy/test_migrations.py:66
#, python-format
msgid "Lock released \"%s\""
msgstr ""

#: savanna/openstack/common/db/sqlalchemy/utils.py:58
msgid "Sort key supplied was not valid."
msgstr "指定されたソート・キーが無効でした。"

#: savanna/openstack/common/db/sqlalchemy/utils.py:97
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr "sort_keys に ID がありません。sort_keys は固有ですか?"

#: savanna/openstack/common/db/sqlalchemy/utils.py:119
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "ソート方向が不明です。'desc' または 'asc' でなければなりません"

#: savanna/openstack/common/db/sqlalchemy/utils.py:194
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""
"col_name_col_instance パラメーターに列 %s を指定してください。これは、列に、sqlite) "
"によってサポートされないタイプがあるために必要です。"

#: savanna/openstack/common/db/sqlalchemy/utils.py:200
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""
"col_name_col_instance パラメーターに、列 %s では正しくないタイプの列インスタンスがあります。これは "
"sqlalchemy.Column のインスタンスでなければなりません。"

#: savanna/openstack/common/db/sqlalchemy/utils.py:280
#, python-format
msgid "Deleting duplicated row with id: %(id)s from table: %(table)s"
msgstr ""

#: savanna/openstack/common/db/sqlalchemy/utils.py:301
msgid "Unsupported id columns type"
msgstr ""

